services:
  - type: web
    name: smart-meeting-tracker-backend
    env: python
    region: singapore
    buildCommand: ./build.sh
    startCommand: gunicorn smart_meeting_tracker.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
