# Generated by Django 6.1.1 on 2026-09-07 07:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discussions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NO_DECISION', 'No Decision'), ('DECISION_MADE', 'Decision Made'), ('DEFERRED', 'Deferred'), ('REJECTED', 'Rejected')], default='NO_DECISION', max_length=20)),
                ('decision', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('decision_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions_made', to=settings.AUTH_USER_MODEL)),
                ('discussion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='discussions.discussion')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('decision_text', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_history_changes', to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='decisions.decision')),
            ],
            options={
                'verbose_name_plural': 'Decision histories',
                'ordering': ['-version'],
            },
        ),
    ]
