# Generated by Django 4.2.30 on 2026-09-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_actionitem_completion_notes_alter_actionitem_assigned_to'),
        ('actions', '0003_add_completion_notes'),
        ('actions', '0004_merge_20260929_1508'),
    ]

    operations = [
    ]
